# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/tags/v2.5.0/configuration-schema.json
package: c87camunda8v2
output: client.c87camunda8v2.gen.go

generate:
  models: true
  client: true
  embedded-spec: true

output-options:
  skip-prune: true
  nullable-type: true
