// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthClient creates a new instance of MockAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthClient {
	mock := &MockAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthClient is an autogenerated mock type for the AuthClient type
type MockAuthClient struct {
	mock.Mock
}

type MockAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthClient) EXPECT() *MockAuthClient_Expecter {
	return &MockAuthClient_Expecter{mock: &_m.Mock}
}

// RetrieveTokenForAPI provides a mock function for the type MockAuthClient
func (_mock *MockAuthClient) RetrieveTokenForAPI(ctx context.Context, target string) (string, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveTokenForAPI")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, target)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthClient_RetrieveTokenForAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveTokenForAPI'
type MockAuthClient_RetrieveTokenForAPI_Call struct {
	*mock.Call
}

// RetrieveTokenForAPI is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockAuthClient_Expecter) RetrieveTokenForAPI(ctx interface{}, target interface{}) *MockAuthClient_RetrieveTokenForAPI_Call {
	return &MockAuthClient_RetrieveTokenForAPI_Call{Call: _e.mock.On("RetrieveTokenForAPI", ctx, target)}
}

func (_c *MockAuthClient_RetrieveTokenForAPI_Call) Run(run func(ctx context.Context, target string)) *MockAuthClient_RetrieveTokenForAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthClient_RetrieveTokenForAPI_Call) Return(s string, err error) *MockAuthClient_RetrieveTokenForAPI_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthClient_RetrieveTokenForAPI_Call) RunAndReturn(run func(ctx context.Context, target string) (string, error)) *MockAuthClient_RetrieveTokenForAPI_Call {
	_c.Call.Return(run)
	return _c
}
