// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmock

import (
	"context"
	"io"

	"github.com/grafvonb/camunder/internal/api/gen/clients/auth/oauth2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenAuthClient creates a new instance of MockGenAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenAuthClient {
	mock := &MockGenAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenAuthClient is an autogenerated mock type for the GenAuthClient type
type MockGenAuthClient struct {
	mock.Mock
}

type MockGenAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenAuthClient) EXPECT() *MockGenAuthClient_Expecter {
	return &MockGenAuthClient_Expecter{mock: &_m.Mock}
}

// RequestTokenWithBodyWithResponse provides a mock function for the type MockGenAuthClient
func (_mock *MockGenAuthClient) RequestTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...oauth2.RequestEditorFn) (*oauth2.RequestTokenResponse, error) {
	var tmpRet mock.Arguments
	if len(reqEditors) > 0 {
		tmpRet = _mock.Called(ctx, contentType, body, reqEditors)
	} else {
		tmpRet = _mock.Called(ctx, contentType, body)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RequestTokenWithBodyWithResponse")
	}

	var r0 *oauth2.RequestTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oauth2.RequestEditorFn) (*oauth2.RequestTokenResponse, error)); ok {
		return returnFunc(ctx, contentType, body, reqEditors...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...oauth2.RequestEditorFn) *oauth2.RequestTokenResponse); ok {
		r0 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth2.RequestTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...oauth2.RequestEditorFn) error); ok {
		r1 = returnFunc(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenAuthClient_RequestTokenWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestTokenWithBodyWithResponse'
type MockGenAuthClient_RequestTokenWithBodyWithResponse_Call struct {
	*mock.Call
}

// RequestTokenWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...auth.RequestEditorFn
func (_e *MockGenAuthClient_Expecter) RequestTokenWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockGenAuthClient_RequestTokenWithBodyWithResponse_Call {
	return &MockGenAuthClient_RequestTokenWithBodyWithResponse_Call{Call: _e.mock.On("RequestTokenWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *MockGenAuthClient_RequestTokenWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...oauth2.RequestEditorFn)) *MockGenAuthClient_RequestTokenWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 []oauth2.RequestEditorFn
		var variadicArgs []oauth2.RequestEditorFn
		if len(args) > 3 {
			variadicArgs = args[3].([]oauth2.RequestEditorFn)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockGenAuthClient_RequestTokenWithBodyWithResponse_Call) Return(requestTokenResponse *oauth2.RequestTokenResponse, err error) *MockGenAuthClient_RequestTokenWithBodyWithResponse_Call {
	_c.Call.Return(requestTokenResponse, err)
	return _c
}

func (_c *MockGenAuthClient_RequestTokenWithBodyWithResponse_Call) RunAndReturn(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...oauth2.RequestEditorFn) (*oauth2.RequestTokenResponse, error)) *MockGenAuthClient_RequestTokenWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}
